version: "3.9"

services:
    web:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:latest
        ports:
            - "${PORT}:80"
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        container_name: ${CONTAINER_NAME}_phpApp
        build: docker/php-fpm
        volumes:
            - ./src:/var/www/html
networks:
  default:
    external: true
    name: "docker-lan"
